# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Make documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  make_docs:
    runs-on:
      group: Default
      labels: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          miniconda-version: "latest"
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Install dependencies
        shell: bash -el {0}
        run: |  
          conda activate
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements-doc.txt ]; then pip install -r requirements-doc.txt; fi
          pip uninstall brainpy -y
          python setup.py install
      - name: Make docs
        shell: bash -el {0}
        run: |
          conda activate
          cd ~/brainpy_docs/docs
          make html